services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: user
      POSTGRES_PASSWORD: admin
    volumes:
      - "./psql:/var/lib/postgresql/data"
